name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: config1
      run: sudo mkdir --parents /opt/gcc-root/lib/gcc/x86_64-linux-gnu
    - name: config2
      run: sudo ln --symbolic /usr/lib/gcc/x86_64-linux-gnu/11 /opt/gcc-root/lib/gcc/x86_64-linux-gnu/11
    - name: config3
      run: sudo ln --symbolic /usr/include /opt/gcc-root/
    - name: config4
      run: export CCC_OVERRIDE_OPTIONS=^--gcc-toolchain=/opt/gcc-root
    - name: config5
      run: export LLVM_COMPILER=clang
    - name: config6
      run: export LLVM_CC_NAM=clang-11
    - name: config7
      run: LLVM_CXX_NAME=clang++-11
    - name: aptUpdate
      run: sudo apt update
    - name: dependencies
      run: sudo apt install ccache clang cmake git graphviz libasound2-dev libgl-dev libqt6opengl6-dev libqt6svg6-dev llvm mold net-tools ninja-build pigz qt6-base-dev rsync tk xterm xxd
    - name: generate
      run:  Make/Linux/generate
    - name: makeSimRobot
      run:  Make/Linux/compile SimRobot
    - name: makeBush
      run:  Make/Linux/compile bush
    - name: makeNao
      run:  Make/Linux/compile Nao
    - name: makeTests
      run:  Make/Linux/compile Tests
    - name: runTests
      run:  ./Build/Linux/Tests/Develop/Tests
